/*#top 10 most rented movie along with their total rental count
#hint: film,inventory,rental*/
select*from film

select*from inventory

select*from rental



select  title,count(rental_id) as total_rental from film as f join inventory  i on f.film_id=i.film_id 
join rental r on i.inventory_id=r.inventory_id group by f.title order by total_rental desc limit 10



 
/*2. Best Customers
 
List the top 5 customers who have spent the most money on rentals.
 
Hint: Use customer, payment, and rental.*/

select first_name,last_name,sum(amount) as rental_money from customer c join payment  p on c.customer_id=p.customer_id 
join rental r on r.rental_id=p.rental_id  group by c.customer_id  order by rental_money desc limit 5

/*3. Revenue by Store
 Calculate the total revenue generated by each store.
 Hint: Join payment, staff, and store.*/
select*from payment

select*from store

select*from staff

select st.store_id,sum(p.amount) as revenue from payment  p join store  st on  p.staff_id=st.manager_staff_id
join staff  s  on p.staff_id=s.staff_id group by st.store_id

/*4. Films by Category
 
Show each film category with the total number of films it contains.
 
Hint: Use film_category and category.*/

select * from  film_category 

select * from  category 

select name,count(film_id) from film_category as f  join category as c on f.category_id=c.category_id group by c.name


/*5. Actor Filmography
For a given actor (say Tom Hanks), list all the films they acted in.
Hint: Use actor, film_actor, and film.*/

select * from actor

select * from film_actor

select * from film

select f.title from film  f join film_actor  fa on  f.film_id=fa.film_id join actor  a on a.actor_id=fa.actor_id
where a.first_name='Ed' and a.last_name='Chase'



/*6. Customers by City
Find how many customers live in each city.
Hint: Join customer, address, and city*/
select *from city 

select *from customer 

select *from address

select  city,count(customer_id) as live_City from city  c join address a on  c.city_id=a.city_id  
join  customer cus on cus.address_id=a.address_id  group by c.city

/*7. Average Rental Duration per Category
 
Find the average rental duration for each film category.
 
Hint: Use film, film_category, and category.*/

select*from category

select * from film_category


select * from film

select name,avg(rental_duration)from category  c  join film_category fc on  fc.category_id=c.category_id 
join film  f  on f.film_id=fc.film_id group by c.name


/*8. Most Popular Film Language
 
Identify which film language is rented the most.
 
Hint: Use film, language, inventory, and rental.*/

select*from language

select*from film

select*from inventory

select*from rental

select  max(name)  from film  f join language l  on  f.language_id=l.language_id  join inventory i on  f.film_id=i.film_id
join rental  r on i.inventory_id=r.inventory_id group by l.name

/*9. Staff Performance
 
Find which staff member processed the most payments and total amount collected.
 
Hint: Use payment and staff.*/
select*from payment

select*from staff

select  first_name,last_name,max(amount),sum(amount)from payment  p join staff  s on p.staff_id=s.staff_id group by s.staff_id

/*10. Overdue Rentals
 
List all rentals that were returned late. Include customer name, film title, rental date, and return date.
 
Hint: Use rental, inventory, film, and customer.*/

select*from film

select*from inventory

select*from customer

select*from rental

select first_name,last_name,title,rental_date,return_date rental_duration from rental as r
join customer as c on r.customer_id=c.customer_id join inventory as i on r.inventory_id=i.inventory_id 
join film as f on f.film_id=i.film_id where   r.return_date > r.rental_date + INTERVAL '1 day' * f.rental_duration









